### ISSUE TITLE
Manglende felter i databasen

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#13]
Etter en tilfeldig gjennomgang av `Create.sql`, så kom jeg på at vi blant annet mangler timestamps på `Forslag`. Det kunne vært greit å ha timestamps for opprettelse, oppdatering, frist og tidspunktet et forslag ble lukket.

Uten disse atributtene, vil det ikke være mulig å vise brukerne når forslagene ble laget, noe som kan gjøre det langt mer utfordrende for teamleder å se hvilke forslag som ble opprettet siden siste møte. Det gjør det også helt umulig å lage statistikk der tid er et parameter (f.eks. uke, måned, år)

Forsåvidt kunne det være greit å lagre dato for opprettelse og oppdatering av brukere, men det er ikke like kritisk som med forslag.

Det kan være greit å gjøre dette tidlig i utviklingen, enten nåværende eller neste scrum-uke. Den eneste endringen vi trenger å foreta oss i modellene er å lage en ekstra linje for datoene, og sette disse til `DateTime.Now` ved opprettelse, oppdatering og lukking. Tror neppe det blir behov for å sette datestamps til en egenvalgt dato, utenom for frister.

Slik jeg forstår det så kan den innebygde `DateTime` være problematisk for rammeverket vi har valgt. Det er likevel fullstendig mulig å lagre datoer. Om vi skulle ha altfor mye problemer med datoer så kan vi bruke Unix Time

https://dev.mysql.com/doc/connector-net/en/connector-net-programming-datetime-problems.html

**Comment by sdushantha** [comment]
Er helt enig. Dette er noe vi må legge til

**Comment by menymo** [comment]
Tenker at @torkelhi har peiling på hvordan dette kan løses, da han har gjort en fantastisk jobb med å lage grunnsteinen til databasen vår. Om ikke han ønsker å gjøre det, så tenker jeg at de som er ansvarlige for forslag gjør dette

Forslags-handler bør tildeles i løpet av neste sprint planning på onsdag

**Comment by Vrolf** [comment]
Er helt enig jeg også, veldig godt forklart @menymo.

**Comment by torkelhi** [comment]
Vi kan gå gjennom hvilke ekstra attributter vi har behov for på mandag.
Vi har behov for å legge til kategori attributt også.
En løsning for problemet relatert til datatypen DateTime er at vi bruker VARCHAR eller CHAR.

**Comment by menymo** [comment]
Hadde frarådet å bruke string-verdier til dato, da dette er mer utfordrende og ressurskrevende å konvertere. Unix time kan lagres som `int`, og konverteres kjempeenkelt til en dato med mer passende format.

I .NET er det også et veldig godt bibliotek for konvertering av talldato til mer lesbare setninger, med mange lokaliseringsfunksjoner.


________________________________
Fra: Torkel Herskedal Ivarsøy ***@***.***>
Sendt: søndag 2. oktober 2022, 5:25 p.m.
Til: IS-200-G7/nordicdoor ***@***.***>
Kopi: Magnus Eugene Nymo ***@***.***>; Mention ***@***.***>
Emne: Re: [IS-200-G7/nordicdoor] Manglende felter i databasen (Issue #13)


Vi kan gå gjennom hvilke ekstra attributter vi har behov for ved mandag.
En løsning for problemet relatert til datatypen DateTime er at vi bruker VARCHAR eller CHAR.

**Comment by sdushantha** [comment]
+1 til unix timestamp
