### ISSUE TITLE
Endre navn i databasen

### ISSUE THREAD

**Issue by Vrolf** [IS-200-G7/nordicdoor#24]
Etter at jeg skulle lage controller for Team, så jeg at team kalles for "Gruppe" i databasen. Etter min mening burde denne fortsatt hete **Team**, da dette gir mer mening. Dette er også terminologi benyttet av NordicDoor, og i oppgavebeskrivelsen.  Team er også helt korrekt å bruke gramatisk i Norge :)

**Comment by menymo** [comment]
Er helt riktig i norsk språk, og jeg synes selv det er mer naturlig

https://naob.no/ordbok/team

**Comment by sdushantha** [comment]
Hvorfor har denne "invalid" taggen?

**Comment by Vrolf** [comment]
Kan godt fjerne den om det er noe problem, description på den er "does not seem right" og i mine øyne gjorde det ikke det @sdushantha

**Comment by menymo** [comment]
Er kanskje heller brukt når selve issuet ikke ser helt riktig ut. Men vi skjønner hva du mener 😄
