### ISSUE TITLE
Lage en build script

### ISSUE THREAD

**Issue by sdushantha** [IS-200-G7/nordicdoor#25]
Tenker det er lurt å ha en build script for både Windows og unix systemer. Denne scripten skal launche en instans av MariaDB i docker og så bygge koden med `dotnet watch run` slik at brukeren slipper å restarte alt når de har endret koden litt

**Comment by sdushantha** [comment]
Burde også ha litt kode som kobler til databasen og kjører SQL scripten for å lage databasen. Da slipper man å kjøre det selv 💡

**Comment by menymo** [comment]
Tror kanskje ikke det blir brukt i utviklingen helt enda, da det er mye jobb å lage en eksempeldatabase. Ihvertfall pleier jeg å bruke samme database hver gang jeg tester koden min, siden vi ikke har noe god måte å lage brukere, grupper og forslag

Det er definitivt verdt å begynne å tenke på `dockerfile` og `docker-compose.yml` til når vi føler at produktet er kinda produksjonsklart

**Comment by sdushantha** [comment]
Går med #27
