### ISSUE TITLE
Legg til dummy data i SQL databasen gjennom scripten?

### ISSUE THREAD

**Issue by sdushantha** [IS-200-G7/nordicdoor#27]
Tenker det er smart å legge til dummy data i SQL data slik at vi har noe å teste med. Da slipper vi å manuelet legge til ting. Dette er spesielt nyttig når man skal få noen andre til å teste koden vår.

**Comment by menymo** [comment]
Tenker det er nice, men ikke helt kritisk. Da burde vi bli enige om en slags standard på dataene. 
Eksempel:
```sql
INSERT INTO Bruker (Fornavn, Etternavn, Email, PassordHash) VALUES ('Jan Terje', 'Navnesen', 'jan.navnesen@nordic.door', '[PASSORDHASH]')
```

Passordhash kan vi bli enige om skal tilsvare samme passord for alle, (f.eks. "ytterdør"). Vi må også tilpasse brukerne etter de ulike user stories, slik at vi har brukere med ulik adgang og eierskap i systemet, blant annet medlem i flere team og forslag med flere medlemmer.

**Comment by sdushantha** [comment]
@IS-200-G7 er kanskje noe vi burde ta opp på mandag? Føler at utvikklingen blir litt lettere då. Alle leker med samme data då

**Comment by menymo** [comment]
Jeg kunne kanskje jobbet med et utkast til dette, for å kompansere litt for sykefraværet mitt

**Comment by tbhansen** [comment]
> Jeg kunne kanskje jobbet med et utkast til dette, for å kompansere litt for sykefraværet mitt

Se gjerne mitt svar [her](https://github.com/IS-200-G7/nordicdoor/issues/34) hvis du skal jobbe med dette @menymo
