### ISSUE TITLE
Liten refaktorering av database 

### ISSUE THREAD

**Issue by Vrolf** [IS-200-G7/nordicdoor#30]
Etter gjennomgang av databasen sammen med @torkelhi og @sdushantha . Har vi kommet frem til en løsning for hvordan vi skal fraskille roller og brukere uten en mange til mange kobling, bildet ligger  [her](https://drive.google.com/drive/folders/1gtly5LfNmRdzM159IapqLQ2aTaaG2eG0). Vi har også kommet frem til at vi ikke har behov for en surrogat nøkkel, når det er mulighet å bruke en sammenslått nøkkel, med andre ord to atributter i stedet for tre i koblingsentiteter.  Dette er også noe Terje har sagt seg enig i, og er tatt opp flere ganger på forelesning.

**Comment by menymo** [comment]
Hvordan vil dette påvirke måten vi lager queries, når det er sammenslåtte nøkler?

**Comment by Vrolf** [comment]
> Hvordan vil dette påvirke måten vi lager queries, når det er sammenslåtte nøkler?

Det er jo fortsatt unikt.
Eg.
xxx.yyy

For søk av x = Team s¨å vil x være unik. For søk av y = bruker vil y være unik.
xxx.yyy som beskriver relasjonen mellom dem er også unik.

**Comment by menymo** [comment]
Har du et eksempel på hvordan man ville søkt på hvilke roller og tilganger en bruker har?

**Comment by Vrolf** [comment]
Akkuratt i dette tilfellet så er det snakk om TeamMedlemskap tabellen, ikke Rolle tabellen.
