### ISSUE TITLE
Kjøre Create.sql når man starter programmet

### ISSUE THREAD

**Issue by sdushantha** [IS-200-G7/nordicdoor#34]
Siden vi bruke `IF NOT EXISTS` så er det jo greit om vi kjører `Create.sql` hver gang når man kjører programmet. Dette er lurt fordi da slipper man å gjør det manuelt.

**Comment by tbhansen** [comment]
Tanke: Når databasen kjøres i Docker så blir det kanskje ikke riktig at programmet kjører `Create.sql`.
Kanskje vi heller skal prøve å lage en docker compose fil som oppretter konteiner, database og [seed data](https://en.wikipedia.org/wiki/Database_seeding) for databasen?

**Comment by sdushantha** [comment]
Er enig, bra tenkt! Docker compose er bedre
