### ISSUE TITLE
Feil med ulike endpoints fra #36

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#37]
Ved testing av PR #36 hadde jeg problemer med noen endpoints:

`GET`: `/api/Team/GetBrukere`
`DELETE`: `/api/Team/DeleteBrukere`

## Expected Behavior

Første endpoint skal returnere en liste over brukere i valgt team.
Andre endpoint skal kunne fjerne en bruker fra valgt team.

## Current Behavior

Får følgende feilmelding:
`MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'nordicdoor.teammedlemskap' doesn't exist`

## Steps to Reproduce

1. Checkout til PR #36 
2. Kjør `Create.sql` i `Server/Database`
3. Sørg for at connection string er korrekt
4. Kjør server og gå inn i Swagger
5. Prøv f.eks. å sende en GET-forespørsel til `/api/Team/GetBrukere` eller DELETE-forespørsel til `/api/Team/DeleteBrukere`

## Possible Implementation

Mulig skrivefeil i `TeamController.cs`, med forveksling av store og små bokstaver

**Comment by Vrolf** [comment]
Denne er allerede resolved og vil være fungerende ved neste oppdatering av PR :)

**Comment by menymo** [comment]
Kan ikke se noen nye commits eller "Resolved conversation". Er det pusha til samme branch som PR?

**Comment by Vrolf** [comment]
Den kommer med neste commit, gi oss 15 minutter
