### ISSUE TITLE
Slette alle "Weather" relaterte filer?

### ISSUE THREAD

**Issue by sdushantha** [IS-200-G7/nordicdoor#40]
Siden vi brukte en template så ligger det en del filer som er relatert til `Weather` endpointen. Dette er jo noe vi ikke trenger å ha i appen.

**Comment by Vrolf** [comment]
Helt enig, det kan slettes 👍

**Comment by menymo** [comment]
Jeg har brukt dem til å teste om jeg har fucka opp :o
