### ISSUE TITLE
Tidssoner og Datatyper

### ISSUE THREAD

**Issue by tbhansen** [IS-200-G7/nordicdoor#50]
**Is your feature request related to a problem? Please describe.**

Tidssoner - LØST
Tiden blir satt utifra Mariadb databasen sin tidssone. Denne kjører på UTC, altså to timer forsinket i forhold til nåværende norsk tidssone. Har nå konkludert med at UTC er korrekt.

Datatyper
Vi benytter oss av datatypen `DATETIME`, som ikke konverterer tidssoner.
https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

**Describe the solution you'd like**
Ved attributter for tidspunkt for opprettelse av brukere/forslag og lignede forslår jeg at vi endrer fra `DATETIME NOT NULL` til `DATETIME DEFAULT CURRENT_TIMESTAMP`.
Ved opprettelse av en ny tuppel (bruker, forslag e.l.) vil tidspunkt bli satt etter databasens daværende tidspunkt. Unngår derfor at curl behøver å inneholde tidspunkt.

Kode for å teste:
```
alter table NordicDoor.Bruker
    modify Opprettet datetime DEFAULT CURRENT_TIMESTAMP;
```

NB: Dette vil også føre til at man må endre litt på controllere.

**Describe alternatives you've considered**
Kan også vurdere å bruke TIMESTAMP. Utifra det jeg vet så vil det utgjøre noen særlig forskjell.

**Additional context**
Kan være vi kan droppe `public DateTime Opprettet { get; set; }` hvis vi endrer til CURRENT_TIMESTAMP;

**Comment by sdushantha** [comment]
Her er svaret: https://mariadb.com/kb/en/time-zones/
Jeg kan fikse dette senere

**Comment by tbhansen** [comment]
Problem med tidssoner er nå løst. Lag ny database og bruk nye kommandoer fra README.txt for å fikse tidssone problematikken.

**Comment by sdushantha** [comment]
> Problem med tidssoner er nå løst. Lag ny database og bruk nye kommandoer fra README.txt for å fikse tidssone problematikken.

@torkelhi @Vrolf @menymo

**Comment by sdushantha** [comment]
@tbhansen beklager, glemte at det var problemer med datatyper også

**Comment by tbhansen** [comment]
**Tanker og mulige problemer rundt tid**

Etter å ha funnet ut hvordan man får mariadb til å benytte seg av norsk tidssone så har jeg blitt usikker på hvordan vi skal gjøre dette med tid. 
Alt. 1: Hendelser kan lagres i UTC i databasen og konverteres til brukerens tidssone ved fremvisning av dato og klokkeslett.
Alt 2: Kan lagre i lokal tidssone. Mulig dette kan føre til problemer dersom det er brukere i ulike tidssoner (mest sannsynlig ikke tilfellet for NordicDoor).

Bør også vurdere å bruke `DateTimeOffset` istedenfor `datetime `, evnt. andre alternativer.

Mitt inntrykk er at det er mange veier til Rom.


https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/
https://ardalis.com/why-use-datetimeoffset/

**Comment by menymo** [comment]
Etter å ha lest artiklene, tenker jeg det er verdt å prøve UTC på både server og database. Velger man UTC, så er det et bedre utgangspunkt for regning til andre tidssoner, da man kan bruke strenger for tidssoner som `Europe/Oslo` eller `Europe/Helsinki`. Nordic Door har kontorer i 3 forskjellige land over 2 tidssoner, og det bør vi ha i bakhodet under utviklingen

**Comment by menymo** [comment]
Issue blir delvis løst av #68

**Comment by menymo** [comment]
@tbhansen Hva er status på datatyper?
