### ISSUE TITLE
Ødelagt endpoint /updateforslag

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#66]
**Describe the bug**
En endpoint i forslagscontrolleren virker ikke som den skal. Den krever at `Status` er definert, og oppdaterer ingen av feltene som blir sendt inn.

**To Reproduce**
1. Checkout til PR #64 
2. Kjør både `create.sql` og `addseeddata.sql`
3. Kjør programmet og gå inn på Swagger
4. Send en forespørsel til `/api/Forslag/updateforslag/{forslagId}`, testdata ligger lenger ned

**Expected behavior**
Endpoint skal oppdatere de spesifiserte feltene i raden definert av `forslagId`

**Logs**
Ingen feilmeldinger

Dersom status ikke er definert, får man en 400 Bad Request:
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-6a28130c264a3381ffa89a54fd9eb8da-c860b0cde8a67e16-00",
  "errors": {
    "Status": [
      "The Status field is required."
    ]
  }
}
```

**Additional context**
Her ligger data jeg testet forespørselen med (ID er satt til `1` eller `2`):
```json
{
  "status": "study",
  "beskrivelse": "oof"
}
```

```json
{
  "status": "plan"
}
```

```json
{
  "emne": "ÆÆÆÆ"
  "status": "study"
}
```

**Comment by menymo** [comment]
Etter siste commit i #64 så vil endpoint returnere riktig objekt, men når jeg etterpå sjekker databasen (enten gjennom API eller direkte i SQL), så vil det fortsatt ligge gammel data

**Comment by EirikBHA** [comment]
![image](https://user-images.githubusercontent.com/89193729/196924957-b4f6330d-d8aa-4434-bac4-1d9e92786719.png)
Får ikke noe feilmelding ved endring av status eller at den krever at status er definert

**Comment by EirikBHA** [comment]
Dataen er også endret i både sql og gjennom datagrip når jeg sjekket nå

**Comment by menymo** [comment]
<img width="946" alt="bilde" src="https://user-images.githubusercontent.com/89194270/196925424-02761040-5088-4fb4-a18d-67a34c633586.png">
Dette er hva som skjer om jeg ikke definerer status

**Comment by EirikBHA** [comment]
Ah ja, du prøver å endre på kun en attributt. Denne funksjonen krever at du endrer alle.

**Comment by EirikBHA** [comment]
Hvis du vil endre kun på en må du fortsatt skrive hva som skal være på de andre, som funksjonen fungerer nå hvertfall.

**Comment by menymo** [comment]
Åja, men hvis det ikke er mulig å endre kun noen få felter, burde man ikke returnere feilmelding da?
Det beste hadde vært om man prøvde å hente ut både feilmelding og resulterende objekt i databasen, for å unngå feil i dataene. Akkurat nå returnerer den bare input

**Comment by EirikBHA** [comment]
Funksjonen var egentlig ment for å oppdatere hele forslaget. Hvis vi tenker å ha funksjoner/funksjon for å endre kun attributter, kan vi fikse det også. PR'en som den er nå er ment som et grunnlag for controlleren med basis CRUD-funksjoner.

**Comment by EirikBHA** [comment]
Den returner også inputet med 200 suksess koden, den tilsier jo da at det funker. Tror kanskje det å hente ut selve objektet kanskje blir litt komplisert.

**Comment by menymo** [comment]
Men 200 skal ikke brukes dersom handler ikke funker, og det er tilfellet når man sender inn ufullstendig data. Da burde den heller returnere 400.

Tror Dapper skal returnere en feilmelding dersom UPDATE ikke kjørte som det skulle, men da må en try-catch implementeres

**Comment by EirikBHA** [comment]
Som skrevet er funksjonen for å endre alt. Hvis vi skal innføre det å kun endre noen ting, må det enten gjøres via en seperat funksjon/funksjoner eller gjennom frontend idk. Ved at det som ikke endres, blir det samme, men likevel oppdatert i databasen sammen med det som faktisk blir endret. Tenkjar hvertfall eg

**Comment by menymo** [comment]
Men det er derfor jeg sier, feilmelding ved ufullstendig data
Den enkle måten å implementere det er å bruke returverdien fra `conn.ExecuteAsync`. 0 betyr feil, 1 betyr ingen feil

**Comment by EirikBHA** [comment]
Hvordan ville du fiksa det?

**Comment by menymo** [comment]
```cs
var resultat = await conn.ExecuteAsync(". . .", forslag);
if (resultat == 0)
{
    return BadRequest();
}
```

**Comment by EirikBHA** [comment]
Så du vil sikre at brukeren sender inn absolutt riktig data?

**Comment by EirikBHA** [comment]
Mtp hva som allerede er i DB og hva de får lov til å sende inn?

**Comment by menymo** [comment]
Hvis bruker sender inn feil data, så returnerer MariaDB en feilmelding, men sånn koden er nå så blir ikke feilmeldingen håndtert, noe som gir en falsk positiv

**Comment by EirikBHA** [comment]
Da må jo det egt implementeres på nesten alle controllerne og funksjonene vi har laget til nå

**Comment by EirikBHA** [comment]
Det er jo ikke det mest prekære å ta tak i akkurat nå, kan være noe vi går tilbake på. Er jo som du sier at det er egentlig bare å sette inn i en try-catch. Viktigste nå er vel at det funker.

**Comment by menymo** [comment]
> Da må jo det egt implementeres på nesten alle controllerne og funksjonene vi har laget til nå

Mange av controllerne våre har allerede implementert noe form for feilhåndtering, eller er designet på en måte som gjør at feil reflekteres av respons. Update på bruker har heller ikke en så veldig god feilhåndtering, men ellers tror jeg de fleste er helt greie

**Comment by EirikBHA** [comment]
Fikser dette senere i sprint 3, bruker det som er nå for å teste ut controller og utvikle frontend.

**Comment by EirikBHA** [comment]
Gjenåpnet for å huske å implementere dette.

**Comment by sdushantha** [comment]
Endpointen funker som den skal gjennom GUI. Får ikke noe feil,æ. Så burde kanskje være alright da?
