### ISSUE TITLE
Navnekonvensjon for pages

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#73]
**Is your feature request related to a problem? Please describe.**
Tenker det kan være lurt å lage en konvensjon om hvordan vi navngir .razor-filer, slik at navnene ikke kolliderer med eksisterende klasser

**Describe the solution you'd like**
Tenker vi kan avslutte navnene framover med `Page`

F.eks `ForslagPage.razor` og `LoginPage.razor`

**Comment by sdushantha** [comment]
I fix

**Comment by EirikBHA** [comment]
Enig

**Comment by menymo** [comment]
Som tidligere nevnt i en lukket PR (#72), så er dette mitt forslag til navngiving:

> `ForslagOverview` = `ForslagPage`
> `ForslagExpanded` = `ForslagModal`
> `ForslagSubmit` = `ForslagForm`

**Comment by sdushantha** [comment]
Fixed
