### ISSUE TITLE
Unødvendig mye bruk av RAM (PassordHash)

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#90]
**Describe the bug**
Akkurat nå virker det som at hashing av et passord tar opptil 6gb med ram. Etter noen timer med debugging sliter jeg med å finne ut akkurat hvorfor koden vår bruker så mye, da et annet testprogram med helt identisk hash-funksjon kjørte på halvparten så mye RAM, selv med samme innstillinger.

Jeg tenker uansett at nåværende innstillinger tar for lang tid, og får innlogging til å virke tregere. Jeg foreslår endringer av enkelte parametre. Endringer av disse vil ødelegge nåværende hashes, og vi bør derfor velge parametre som kommer til å virke i framtiden.

**Desktop:**
 - OS: MacOS 12.4
 - CPU: Apple M1
 - Modell: MacBookPro17,1

**Additional context**
Her ligger noen målinger av hvor lang tid hashing tar for hver `MemorySize`. Gjennomsnittet er kalkulert fra 3 tester. Nåværende konfigurasjon (1GB) ligger nederst, da den tar nesten 2 sekunder

***128MB***
- 00:00:00.3987710
- 00:00:00.1901370
- 00:00:00.2007020

Avg: 00:00:00.2632033

***256MB***
- 00:00:00.6464200
- 00:00:00.4259590
- 00:00:00.4028570

Avg: 00:00:00.4917453

***512MB***
- 00:00:01.0622610
- 00:00:00.8236140
- 00:00:00.8448550

Avg: 00:00:00.9102433

***768MB***
- 00:00:01.4885060
- 00:00:01.2201640
- 00:00:01.1929330

Avg: 00:00:01.3005343

***1GB (nåværende)***
- 00:00:01.9139610
- 00:00:01.6316320
- 00:00:01.5381860

Avg: 00:00:01.6945930

**Comment by Vrolf** [comment]
Fint beskrevet Magnus, når jeg bruker controlleren din tar det ca 4 sekunder før den endrer passord. Men husk også at det viktigeste er at det fungerer, jeg er helt sikker på at slik det er nå ikke vil virke negativt på eksamen.

**Comment by menymo** [comment]
Tror ikke vi er garantert å få det på eksamen, men litt kleint om vi blir spurt om den enorme RAM-bruken. Også er det litt dumt om alt crasher i demoen fordi man gikk tom for RAM

Ev. så kan man endre på andre innstillinger for å kompansere for mindre prosseseringskraft brukt, og begrunne det med sikkerhet

**Comment by menymo** [comment]
Her ligger koden jeg brukte for mine (ikke så vitenskapelige) tester av Argon2:

[https://github.com/IS-200-G7/argon2-timer](https://github.com/IS-200-G7/argon2-timer)

**Comment by EirikBHA** [comment]
Denne er vel fikset nå

**Comment by menymo** [comment]
@EirikBHA Den er ikke fikset. Ingen har reviewet koden, og jeg har derfor ikke fått merget det.

Når PR #91 er merget, så lukkes dette automatisk

**Comment by EirikBHA** [comment]
Aaaah trodde den var merget, my bad
