### ISSUE TITLE
Feil datatype på endpoint

### ISSUE THREAD

**Issue by menymo** [IS-200-G7/nordicdoor#93]
**Describe the bug**
`/api/Bruker/{AnsattNr}`

Endpoint returnerer en `List<Bruker>`, selv om den egentlig bare skal returnere `Bruker`

**To Reproduce**
1. Åpne swagger
2. Send en gyldig forespørsel til nevnt endpoint
3. Resultat begynner med `[` og slutter på `]`, og har selve brukerobjektet i det. Dette indikerer `List`

**Additional context**
https://github.com/IS-200-G7/nordicdoor/blob/d493a04b1553d420a461c8d48675855f3d393117/PDSA_System/Server/Controllers/BrukerController.cs#L37-L52

Dette kan fikses ved at controlleren endres slik: (merk at delen med `List`) er fjernet
```cs
public async Task<ActionResult<Bruker>> GetBruker(int AnsattNr)
```

Da må også den siste linjen i funksjonen endres slik: (navn på variabel endret til entall)
```cs
return Ok(bruker.First());
```

**Comment by EirikBHA** [comment]
Skal få sjekket det!

**Comment by menymo** [comment]
Etter nærmere gjennomgang viser det seg at mange controllers har denne feilen. I tillegg er det flere andre typer endpoints som ikke trenger en `List` for å representere all dataen

https://github.com/IS-200-G7/nordicdoor/blob/d493a04b1553d420a461c8d48675855f3d393117/PDSA_System/Server/Controllers/ForslagController.cs#L37-L51

https://github.com/IS-200-G7/nordicdoor/blob/d493a04b1553d420a461c8d48675855f3d393117/PDSA_System/Server/Controllers/TeamController.cs#L32-L44

**Comment by EirikBHA** [comment]
Fikk du denne til å fungere med din versjon av LoginPage?

**Comment by menymo** [comment]
LoginPage brukte string, så jeg fikk aldri noe feil der angående datatype. Er først nå som vi har komplekse objekter at det har blitt et problem

________________________________

**Comment by EirikBHA** [comment]
Ja får feilmelding selv, kan se på d mer på gruppearbeidet nå etterpå
